// Fail ini dijana OTOMATIK oleh dashboard — jangan edit tangan.
const produk = [
  { nama:"Shaker Bar 350ml — Best Seller Borong", cat:"bawah4", harga:1.53, tier:"RM1.53/unit • 1 bag = 104pcs", cover:"images/covers/sport-shaker.jpg", asal:"images/lYPtSu926Sp4kYv7kRZg24fXxHsm5YTpuMjn3koO.jpg", desc:"Direct WhatsApp RM1.53/unit (min 1 bag = 104pcs). Platform Shopee/TikTok/Lazada RM2.45 — jimat RM0.92/unit. Pelanggan repeat order tiap bulan!" },
  { nama:"Botol Minum Sport — Sekali Tekan Terus Buka", cat:"bawah4", harga:3.0, tier:"RM3.40 / RM3.20 / RM3.00", cover:"images/covers/snap-lid.jpg", asal:"images/9ef9R5bb4mh9RKIRhGYLqGVi1vdsBJvMWNuaQwIC.jpg", desc:"Untuk gym, sekolah, aktiviti luar. Senang buka tutup, muat dalam beg. Jimat borong, untung jual balik." },
  { nama:"Tumbler Premium — Nampak Mahal, Harga Borong", cat:"bawah4", harga:3.2, tier:"RM3.50 / RM3.30 / RM3.20", cover:"images/covers/elegant-tumbler.jpg", asal:"images/qcY0xfyG8CkCuXHxe9HHEcFuxUoYGlHxa9cEIDbO.jpg", desc:"Gaya premium tapi harga kilang. Pelanggan suka repeat sebab nampak eksklusif." },
  { nama:"Cawan Plastik Teguh — Tak Mudah Pecah", cat:"bawah2", harga:1.6, tier:"RM1.80 / RM1.70 / RM1.60", cover:"images/covers/solid-cup.jpg", asal:"images/gsM2OMtBUZppvtFbSkKNGuwJRYKHPydNi9wEZ2FE.jpg", desc:"Tebal dan tahan lasak. Sesuai untuk katering, kedai makan, atau jual balik." },
  { nama:"Cawan Mini Bintang — Comel, Anak-Anak Suka", cat:"bawah2", harga:1.6, tier:"RM1.80 / RM1.70 / RM1.60", cover:"images/covers/star-mini.jpg", asal:"images/oTFhLG2zaozg6O5p8zKGulb5Dip8D3TNjQ2zMNRf.jpg", desc:"Saiz kecil untuk budak-budak, corak bintang tarik perhatian. Untung jual bundle." },
  { nama:"Cawan Warna-Warni — Semua Warna, Semua Suka", cat:"bawah2", harga:0.9, tier:"RM1.40 / RM1.10 / RM0.90", cover:"images/covers/colorful-cup.jpg", asal:"images/fl50YsNtrRp32fQkDJm6gs19uOis3UkcHqxMUaT9.jpg", desc:"Campur warna dalam satu order. Sesuai untuk goodie bag dan gift set." },
  { nama:"Botol Mini Glossy — Nampak Mahal Tapi Murah", cat:"bawah2", harga:1.6, tier:"RM1.80 / RM1.70 / RM1.60", cover:"images/covers/glossy-mini.jpg", asal:"images/lNwXeM12frOokCTgL2pLWxRlLLcwD0Pp34lUs94c.jpg", desc:"Kemasan berkilat, feel premium. Saiz mini sesuai untuk hadiah, door gift, sample." },
  { nama:"Botol Bening — Nampak Isi, Senang Jual", cat:"bawah2", harga:1.6, tier:"RM1.80 / RM1.70 / RM1.60", cover:"images/covers/transparent.jpg", asal:"images/peXeKK9s65BMNMCexKSuwkfdAd46JdgKEwlfa9gf.jpg", desc:"Transparent, nampak isi dalam. Pelanggan farmasi & ubat suka jenis ni." },
  { nama:"Botol Klip — Tutup Sekali Klip, Confirm Tak Tumpah", cat:"bawah2", harga:1.3, tier:"RM1.50 / RM1.40 / RM1.30", cover:"images/covers/clip-lids.jpg", asal:"images/mDY8V2NR9ZXZSP37CH0ffkuBgsR9qZoyAZ2bZf0X.jpg", desc:"Klip ketat, selamat dibawa travel. Senang buka tutup." },
  { nama:"Botol Dua Ruang — Campur Rasa, Satu Botol Dua Fungsi", cat:"bawah4", harga:2.69, tier:"RM2.89 / RM2.79 / RM2.69", cover:"images/covers/double-cup.jpg", asal:"images/PBjB4I6Lb0k1Kd0bzv3VLAd5jhOcJCrlPYciuiMO.jpg", desc:"Isi 2 minuman berbeza dalam satu botol. Unik dan fast-moving untuk jualan runcit." },
  { nama:"Botol Dua Ruang + Gagang — Senang Bawa, Style Abis", cat:"bawah4", harga:2.9, tier:"RM3.10 / RM3.00 / RM2.90", cover:"images/covers/double-cup-handle.jpg", asal:"images/CLRu2ISxwrqTwAREJ5SWPsmNKmSVZf5vWpboQtbs.jpg", desc:"Macam botol dua ruang tapi ada pemegang. Convenient, senang jual bundle." },
];
const catLabel = { bawah2:"Bawah RM2", bawah4:"Bawah RM4" };
